#!/bin/bash

if [ -z "$1" ] 
then
	echo "missing commit message"
	exit 1
else 
	msg=$1
fi

echo "Adding all files..."
git add --all
echo "Add complete. Committing with message: '$msg'..."
git commit -m "$msg"
echo "Commit completed. Pushing to remote repo..."
git push
echo "Push completed. All operations completed."

exit 0





