#!/bin/bash

if [ -z "$1" ] 
then
	echo "missing commit message"
	exit 1
else 
	msg=$1
fi


add="git add --all"
commit="git commit -m \"$msg\""
echo $commit
push="git push"

$add
#$commit
git commit -m "$msg"
$push

exit 0





