#!/bin/bash

if [ -z "$1" ] 
then
	echo "missing commit message"
	exit 1
else 
	msg=$1
fi

echo "Adding all files, commit with message: '$msg', pushing to remote repo."

git add --all
git commit -m "$msg"
git push

exit 0





