#!/bin/bash

if [ -z "$1" ] 
then
	echo "missing folder name"
	exit 1
else 
	name=$1
fi

echo "Changing path to ~/Desktop/Extra/leetcode..."
cd ~/Desktop/Extra/leetcode
echo "Changed path. Creating folder..."
mkdir "$name"
echo "Folder created. Changing path to the new folder..."
cd "$name"
echo "Creating file Solution.scala..."
touch Solution.scala
echo "File created. Opening Visual Studio Code..."
code .
echo "Completed."

exit 0





